name: movies_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  http: ^0.13.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  google_fonts: ^4.0.1
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/languages/
    - assets/animations/

